### ISSUE TITLE
Feature request: Paypal T-Code Description

### ISSUE THREAD

**Issue by mbehrle** [willuhn/hibiscus.paypal#6]
Momentan wird nur eine Teilmenge der T-Codes ausgewertet und als Beschreibung in den Verwendungszweck geschrieben. Für nachfilternde Software wie z.B. das [Tyton Hibiscusmodul](https://gitlab.com/m9s/account_banking_import_hibiscus) wäre es sehr hilfreich, prinzipiell eine Beschreibung des T-Codes im Hibiscusdatensatz mitgeliefert zu bekommen.

Ich habe eine Liste aus der [Transaction event code (T-code) reference](https://developer.paypal.com/docs/reports/reference/tcodes/) erstellt und angehängt [Paypal_tcodes.ods](https://github.com/willuhn/hibiscus.paypal/files/13040120/Paypal_tcodes.ods).

Ich fände es super, wenn die Beschreibung aus einer solchen Liste gezogen würde, wenn keine anderweitige Beschreibung im Verwendungszweck steht.

Leider bin ich in Java sehr wenig zu Hause...:(, von daher kann ich leider selbst keinen PR erstellen.

**Comment by willuhn** [comment]
Ich verstehe nicht so richtig, was genau du dir jetzt wünschst. Wo genau soll die Beschreibung hin?

**Comment by mbehrle** [comment]
So weit ich das sehe, werden momentan einige Fälle ab https://github.com/willuhn/hibiscus.paypal/blob/ce869a682971588ace1973e8857335ae2594f642/src/de/willuhn/jameica/hbci/paypal/synchronize/PaypalSynchronizeJobKontoauszug.java#L390
abgehandelt. Die entsprechenden Beschreibungen sind allerdings als deutsches Äquivalent kodiert.

Ich sehe mehrere Möglichkeiten:
1) Wenn man diese deutschen Äquivalente beibehalten will, könnte man eine else Bedingung einbauen, die den englischen Begriff nimmt, falls keine deutsche gefunden wurde.
2) Wenn man auf die deutschen Äquivalente verzichten würde, könnte man prinzipiell die Beschreibung des T-Codes in den Verwendungszweck schreiben.
3) Man schreibt die Bezeichnung des T-Codes prinzipiell ins Notizfeldfeld (dazu).

**Comment by willuhn** [comment]
Meinst du damit, das Plugin solle intern eine Liste all dieser Codes enthalten, in der sich die deutschen und englischen Beschreibungen all der Codes finden und das Plugin im erstellten Hibiscus-Umsatz den von Paypal übertragenen Code um den zugehörigen Beschreibungstext aus dieser Liste ergänzt?

**Comment by mbehrle** [comment]
Im Prinzip ja. 

Das Problem sind z.B. Buchungen, wo ein T-Code drin steht und sonst nichts. 
Für die Filterung ist der T-Code in Feld 'Art' ideal, allerdings will man nicht jedes Mal auf die Referenzseite von Paypal gehen (bzw. die Benutzer da hin verweisen), um die Bedeutung dieser Codes nachzuschlagen.

Von daher wäre für mich vorrangig, für jeden T-Code dessen Beschreibung (z.B. in Verwendungszweck oder Notiz) mitgeliefert zu bekommen. Auf jeden Fall in englisch, eine deutsche Übersetzung wäre ein zusätzliches Plus.

**Comment by mbehrle** [comment]
https://github.com/willuhn/hibiscus.paypal/pull/10 merged
