### ISSUE TITLE
Doppelte Einträge in Verwendungszweck

### ISSUE THREAD

**Issue by mbehrle** [willuhn/hibiscus.paypal#7]
Im Verwendungszweck steht bei z.B. ExpressCheckout-Zahlungen ein duplizierter Eintrag wie z.B.
Sale ID: 2191 (Name)Sale ID: 2191 (Name)

**Comment by willuhn** [comment]
Das hat Paypal dann genauso übertragen. Ich finde im Code keine Stelle, wo zwei gleiche Strings in der Form im Verwendungszweck gespeichert werden.

**Comment by mbehrle** [comment]
Im Richter-Plugin ist das allerdings anders. Ich hatte vermutet, ob vielleicht [Codezeile](https://github.com/willuhn/hibiscus.paypal/blob/ce869a682971588ace1973e8857335ae2594f642/src/de/willuhn/jameica/hbci/paypal/synchronize/PaypalSynchronizeJobKontoauszug.java#L338) nicht wie gewünscht funktioniert.
Könnte es sein, dass `!ti.transaction_note.equals(ti.transaction_subject)` nicht funktioniert, weil u.U. eine Zeichenkette mit Leerzeichen endet o.ä.?

**Comment by willuhn** [comment]
Das Plugin von Sebastian verwendet eine andere Schnittstelle. Da kann es im Verhalten durchaus Unterschiede geben.
Die genannte Zeile kann in der Tat eine mögliche Ursache sein. Ich habe selbst allerdings keinen eigenen Paypal-Account, mit dem ich sowas testen kann. Ich habe daher mal mehr oder weniger blind zwei "trim()" eingefügt. Kannst du das bitte mal testen?

Falls das nicht die Ursache ist: Kannst du mit deinem Account bitte mal debuggen?

**Comment by mbehrle** [comment]
Das wird dann in der nightly morgen enthalten sein?

Ich werde das dann testen, indem ich 1) Umsätze lösche 2) Saldo zurücksetze 3) neu importiere. Richtig?

Für weiteres Debugging muss du mich an die Hand nehmen, weil ich wie gesagt ein Java-Noob bin.

**Comment by willuhn** [comment]
Jepp. Ist morgen im Nightly Build. Zum Debuggen: Schau dir mal https://www.willuhn.de/wiki/doku.php?id=develop:eclipse an. Da ist beschrieben, wie du Hibiscus in Eclipse einrichten kannst. Das selbe kannst du dann auch zusätzlich mit hibiscus.paypal machen.

**Comment by mbehrle** [comment]
Habe jetzt mit dem nightly build vom 21.10. getestet, hat sich leider nichts geändert. Ohne Debugging, was wirklich in ti.transaction_note und ti.transaction_subject geliefert wird, fischt man nur im Trüben. Ich versuche mal das Debugging in einer freien Minute aufzusetzen.
