### ISSUE TITLE
Fehlendes Leerzeichen bei zusammengesetzten Einträgen im Verwendungszweck

### ISSUE THREAD

**Issue by mbehrle** [willuhn/hibiscus.paypal#8]
Beispiel: Bestellnummer : 08-10621-87188Einkaufsbetrag

Minor issue, kann aber wichtig für das Parsen dieser Strings sein.

**Comment by willuhn** [comment]
Das hat Paypal dann genauso übertragen. Ich finde im Code keine Stelle, wo zwei Strings ohne Leerzeichen dazwischen zusammen in einer Zeile des Verwendungszwecks gespeichert werden.
